[project]
name = 'Decentralized-Bug-Bounty'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bug-bounty]
path = 'contracts/bug-bounty.clar'
clarity_version = 2
epoch = 2.5

[contracts.decentralized-charity]
path = 'contracts/decentralized-charity.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputation_clar]
path = 'contracts/reputation_clar.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
